### PR TITLE
Added MN student organizations

### PR DESCRIPTION
**Pull request by delaineackerman**
I added three University of Minnesota student organizations to the University-Student-Organizations.md file.

### CODE REVIEW

**Comment by aceyoung9** [comment]
Hi @delainewendling,

Do you mind fixing the merge conflicts? They're probably being caused by the space characters that were removed in the first commit, then added again in the second one.

**Comment by delaineackerman** [comment]
@aliceyoung9 No problem!

**Comment by delaineackerman** [comment]
@aliceyoung9 Should be good to go now

**Comment by aceyoung9** [comment]
Thanks!

**Pull request merged**
