### PR TITLE
added hackathon glossary

### PR DESCRIPTION
**Pull request by seankross**

### CODE REVIEW

**Comment by aceyoung9** [comment]
@seankross Mind separating the Hackathon Glossary into its own markdown file?

**Comment by seankross** [comment]
@aliceyoung9 No problem. Should it be in its own directory or should it be in the top directory?

**Comment by aceyoung9** [comment]
@seankross Eh, just put it in the top directory.

**Comment by seankross** [comment]
@aliceyoung9 let me know if you'd like me to make any other changes. I plan on contributing more definitions. Also please let me know if there's something you don't like about a definition, or if there's anything else I can do to help.

**Pull request merged**
