### PR TITLE
Updated with Illinois/Northwestern University

### PR DESCRIPTION
**Pull request by alainakafkes**
Added Women in Computing & BuildHer

### CODE REVIEW

**Comment by aceyoung9** [comment]
Thanks!

**Comment by alainakafkes** [comment]
Thank you @aliceyoung9 ! I have a quick question -- would it be possible for me to be added a contributor to LSH on GitHub? I'd like to add a new document about how to start/run a mentorship program.

**Comment by aceyoung9** [comment]
Alrighty! Member invite sent, @alainakafkes ! I'm on the Slack too, if you need anything.

**Comment by alainakafkes** [comment]
@aliceyoung9 Thanks! :) For some reason, I don't have access to creating repositories -- do you know how to edit that?

**Pull request merged**
